<?php

/**
 * Baseschool_year
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $value
 * @property date $start_at
 * @property date $end_at
 * 
 * @method string      getValue()    Returns the current record's "value" value
 * @method date        getStartAt()  Returns the current record's "start_at" value
 * @method date        getEndAt()    Returns the current record's "end_at" value
 * @method school_year setValue()    Sets the current record's "value" value
 * @method school_year setStartAt()  Sets the current record's "start_at" value
 * @method school_year setEndAt()    Sets the current record's "end_at" value
 * 
 * @package    ubeo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseschool_year extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('school_year');
        $this->hasColumn('value', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('start_at', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('end_at', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}