<?php

/**
 * Basestudent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $student_code
 * @property integer $user_id
 * @property string $thumb
 * @property Doctrine_Collection $student_groups
 * @property Doctrine_Collection $student_fields
 * 
 * @method string              getStudentCode()    Returns the current record's "student_code" value
 * @method integer             getUserId()         Returns the current record's "user_id" value
 * @method string              getThumb()          Returns the current record's "thumb" value
 * @method Doctrine_Collection getStudentGroups()  Returns the current record's "student_groups" collection
 * @method Doctrine_Collection getStudentFields()  Returns the current record's "student_fields" collection
 * @method student             setStudentCode()    Sets the current record's "student_code" value
 * @method student             setUserId()         Sets the current record's "user_id" value
 * @method student             setThumb()          Sets the current record's "thumb" value
 * @method student             setStudentGroups()  Sets the current record's "student_groups" collection
 * @method student             setStudentFields()  Sets the current record's "student_fields" collection
 * 
 * @package    ubeo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basestudent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('student');
        $this->hasColumn('student_code', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('thumb', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('student_groups', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $this->hasMany('student_fields', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}