<?php

/**
 * Basestudent_angi
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $student_id
 * @property integer $school_year_id
 * @property integer $angi_id
 * @property student $student
 * @property school_year $school_year
 * @property angi $angi
 * 
 * @method integer      getStudentId()      Returns the current record's "student_id" value
 * @method integer      getSchoolYearId()   Returns the current record's "school_year_id" value
 * @method integer      getAngiId()         Returns the current record's "angi_id" value
 * @method student      getStudent()        Returns the current record's "student" value
 * @method school_year  getSchoolYear()     Returns the current record's "school_year" value
 * @method angi         getAngi()           Returns the current record's "angi" value
 * @method student_angi setStudentId()      Sets the current record's "student_id" value
 * @method student_angi setSchoolYearId()   Sets the current record's "school_year_id" value
 * @method student_angi setAngiId()         Sets the current record's "angi_id" value
 * @method student_angi setStudent()        Sets the current record's "student" value
 * @method student_angi setSchoolYear()     Sets the current record's "school_year" value
 * @method student_angi setAngi()           Sets the current record's "angi" value
 * 
 * @package    ubeo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basestudent_angi extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('student_angi');
        $this->hasColumn('student_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('school_year_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('angi_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('student', array(
             'local' => 'student_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('school_year', array(
             'local' => 'school_year_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('angi', array(
             'local' => 'angi_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}