<?php

/**
 * Basestudent_fields
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $student_id
 * @property integer $field_id
 * @property object $value
 * @property student $student
 * @property fields $fields
 * 
 * @method integer        getStudentId()  Returns the current record's "student_id" value
 * @method integer        getFieldId()    Returns the current record's "field_id" value
 * @method object         getValue()      Returns the current record's "value" value
 * @method student        getStudent()    Returns the current record's "student" value
 * @method fields         getFields()     Returns the current record's "fields" value
 * @method student_fields setStudentId()  Sets the current record's "student_id" value
 * @method student_fields setFieldId()    Sets the current record's "field_id" value
 * @method student_fields setValue()      Sets the current record's "value" value
 * @method student_fields setStudent()    Sets the current record's "student" value
 * @method student_fields setFields()     Sets the current record's "fields" value
 * 
 * @package    ubeo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basestudent_fields extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('student_fields');
        $this->hasColumn('student_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('field_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('value', 'object', null, array(
             'type' => 'object',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('student', array(
             'local' => 'student_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('fields', array(
             'local' => 'field_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}