<?php

/**
 * Basestudent_group
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $student_id
 * @property integer $school_year_id
 * @property integer $group_id
 * @property student $student
 * @property school_year $school_year
 * @property st_group $st_group
 * 
 * @method integer       getStudentId()      Returns the current record's "student_id" value
 * @method integer       getSchoolYearId()   Returns the current record's "school_year_id" value
 * @method integer       getGroupId()        Returns the current record's "group_id" value
 * @method student       getStudent()        Returns the current record's "student" value
 * @method school_year   getSchoolYear()     Returns the current record's "school_year" value
 * @method st_group      getStGroup()        Returns the current record's "st_group" value
 * @method student_group setStudentId()      Sets the current record's "student_id" value
 * @method student_group setSchoolYearId()   Sets the current record's "school_year_id" value
 * @method student_group setGroupId()        Sets the current record's "group_id" value
 * @method student_group setStudent()        Sets the current record's "student" value
 * @method student_group setSchoolYear()     Sets the current record's "school_year" value
 * @method student_group setStGroup()        Sets the current record's "st_group" value
 * 
 * @package    ubeo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basestudent_group extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('student_group');
        $this->hasColumn('student_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('school_year_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('student', array(
             'local' => 'student_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('school_year', array(
             'local' => 'school_year_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('st_group', array(
             'local' => 'group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}