<?php

/**
 * Basestudent_groups
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $student_id
 * @property integer $school_year_id
 * @property integer $groups_id
 * @property student $student
 * @property school_year $school_year
 * @property stgroups $stgroups
 * 
 * @method integer        getStudentId()      Returns the current record's "student_id" value
 * @method integer        getSchoolYearId()   Returns the current record's "school_year_id" value
 * @method integer        getGroupsId()       Returns the current record's "groups_id" value
 * @method student        getStudent()        Returns the current record's "student" value
 * @method school_year    getSchoolYear()     Returns the current record's "school_year" value
 * @method stgroups       getStgroups()       Returns the current record's "stgroups" value
 * @method student_groups setStudentId()      Sets the current record's "student_id" value
 * @method student_groups setSchoolYearId()   Sets the current record's "school_year_id" value
 * @method student_groups setGroupsId()       Sets the current record's "groups_id" value
 * @method student_groups setStudent()        Sets the current record's "student" value
 * @method student_groups setSchoolYear()     Sets the current record's "school_year" value
 * @method student_groups setStgroups()       Sets the current record's "stgroups" value
 * 
 * @package    ubeo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basestudent_groups extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('student_groups');
        $this->hasColumn('student_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('school_year_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('groups_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('student', array(
             'local' => 'student_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('school_year', array(
             'local' => 'school_year_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('stgroups', array(
             'local' => 'groups_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}