# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [utopia-white.css, utopia-responsive, fullcalendar.css, main.css]

  javascripts:    [jquery.min.js, jquery.cookie.js, utopia.js, jquery.hoverIntent.min.js, jquery.easing.1.3.js, jquery.datatable.js, fullcalendar.js, jquery.sparkline.js, jquery.vticker-min.js, datepicker.js, image-gallery.min.js, jquery.simpleWeather.js, maskedinput.js, chosen.jquery.js, sidebar.js, load-image.min.js, jquery.validationEngine.js, jquery.validationEngine-en.js, jquery.queryloader2.js, header.js ]

  has_layout:     true
  layout:         layout
