<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/07/20 09:39:01

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=ubeo',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
