<?php

/**
 * angiTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class angiTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object angiTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('angi');
    }
}