<?php

/**
 * fieldsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class fieldsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object fieldsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('fields');
    }
}