<?php

/**
 * field_valuesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class field_valuesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object field_valuesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('field_values');
    }
}