<?php

/**
 * groupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class groupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object groupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('group');
    }
}