<?php

/**
 * lesson_fieldsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class lesson_fieldsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object lesson_fieldsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('lesson_fields');
    }
}