<?php

/**
 * lessonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class lessonTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object lessonTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('lesson');
    }
}