<?php

/**
 * school_yearTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class school_yearTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object school_yearTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('school_year');
    }
}