<?php

/**
 * school_year_termTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class school_year_termTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object school_year_termTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('school_year_term');
    }
}