<?php

/**
 * st_groupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class st_groupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object st_groupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('st_group');
    }
}