<?php

/**
 * stgroupsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class stgroupsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object stgroupsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('stgroups');
    }
}