<?php

/**
 * student_groupsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class student_groupsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object student_groupsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('student_groups');
    }
}