<?php

/**
 * student_fieldsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class student_fieldsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object student_fieldsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('student_fields');
    }
}