<?php

/**
 * student_groupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class student_groupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object student_groupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('student_group');
    }
}