<?php

/**
 * student_angi
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ubeo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class student_angi extends Basestudent_angi
{

}