<?php

/**
 * teacher_fieldsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class teacher_fieldsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object teacher_fieldsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('teacher_fields');
    }
}