<?php

/**
 * teacher_form_fieldsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class teacher_form_fieldsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object teacher_form_fieldsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('teacher_form_fields');
    }
}