<?php

/**
 * termTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class termTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object termTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('term');
    }
}