<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/07/23 10:06:49
sfConfig::add(array(
  'mod_student_form_fields_enabled' => true,
  'mod_student_form_fields_view_class' => 'sfPHP',
));
