<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/07/22 10:55:34
sfConfig::add(array(
  'mod_school_year_term_enabled' => true,
  'mod_school_year_term_view_class' => 'sfPHP',
));
