generator:
  class: sfDoctrineGenerator
  param:
    model_class:           field_values
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          field_values
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  
        class: false
      form:    
        display: [field_id, value, fielvaluedorder]
      edit:    ~
      new:     ~
