#  Fields Table
fields:
  actAs: 
    Timestampable: ~
  columns:
    fieldname: { type: string(255), notnull: true}
    fieldtype: { type: string(255), notnull: true} 
    fieldkey: { type: string(255), notnull: true, default: 'field_key'}   
    fieldorder: { type: integer, notnull: false, default: 0 }
    isNum: { type: integer, notnull: false, default: 0 }
    isReq: { type: integer, notnull: false, default: 0 }

    
#  Field Values Table
field_values:
  actAs: 
    Timestampable: ~
  columns:
    value: { type: string(255), notnull: true}
    field_id: { type: integer, notnull: true }
    fielvaluedorder: { type: integer, notnull: false, default: 0 }    
  relations:
    fields: {onDelete: CASCADE, local: field_id, foreign: id}  

#  Term Table
term:
  actAs: 
    Timestampable: ~
  columns:
    value: { type: string(255), notnull: true}
    start_at: { type: date, notnull: true}
    end_at: { type: date, notnull: true }


#  School Year Table
school_year:
  actAs: 
    Timestampable: ~
  columns:
    value: { type: string(255), notnull: true}
    start_at: { type: date, notnull: true}
    end_at: { type: date, notnull: true }

# School year Term Table
school_year_term:
  actAs: 
    Timestampable: ~
  columns:
    term_id: { type: integer, notnull: true }
    school_year_id: { type: integer, notnull: true }    
  relations:
    term: {onDelete: CASCADE, local: term_id, foreign: id}   
    school_year: {onDelete: CASCADE, local: school_year_id, foreign: id}   
    
#  angi
angi:
  actAs: 
    Timestampable: ~
  columns:
    short_name: { type: string(10), notnull: true }
    name: { type: string(255), notnull: true }    

#  Student Table
student:
  actAs:
    Timestampable: ~
  columns:
    student_code: { type: string(255), notnull: true}
    user_id: { type: integer, notnull: true }
    thumb: { type: string(255) }
  relations:
    sf_guard_user: {onDelete: CASCADE, local: user_id, foreign: id}

student_angi:
  actAs: 
    Timestampable: ~
  columns:
    student_id: { type: integer, notnull: true }
    school_year_id: { type: integer, notnull: true } 
    angi_id: { type: integer, notnull: true } 
  relations:
    student: {onDelete: CASCADE, local: student_id, foreign: id}
    school_year: {onDelete: CASCADE, local: school_year_id, foreign: id}
    angi: {onDelete: CASCADE, local: angi_id, foreign: id}
#  Student Fields Table   
student_fields:
   actAs:
    Timestampable: ~
   columns:
    student_id: { type: integer, notnull: true}
    field_id: { type: integer, notnull: true }
    value: { type: object, notnull: true }
   relations:
    student: {onDelete: CASCADE, local: student_id, foreign: id}
    fields: {onDelete: CASCADE, local: field_id, foreign: id}
#  Teacher Table
teacher:
  actAs:
    Timestampable: ~
  columns:
    student_code: { type: string(255), notnull: true}
    user_id: { type: integer, notnull: true }
    thumb: { type: string(255) }
  relations:
    sf_guard_user: {onDelete: CASCADE, local: user_id, foreign: id}
#  Teacher Fields Table
teacher_fields:
   actAs:
    Timestampable: ~
   columns:
    teacher_id: { type: integer, notnull: true}
    field_id: { type: integer, notnull: true }
    value: { type: object, notnull: true }
   relations:
    teacher: {onDelete: CASCADE, local: teacher_id, foreign: id}
    fields: {onDelete: CASCADE, local: field_id, foreign: id}
#  Lesson Table
lesson:
  actAs:
    Timestampable: ~
  columns:
    lesson_code: { type: string(255), notnull: true}
    prev_lesson: { type: integer, notnull: false }
  relations:
    sf_guard_user: {onDelete: CASCADE, local: user_id, foreign: id}
    lesson: {onDelete: CASCADE, local: prev_lesson, foreign: id}
    
    
    
#  lesson Fields Table
lesson_fields:
   actAs:
    Timestampable: ~
   columns:
    lesson_id: { type: integer, notnull: true}
    field_id: { type: integer, notnull: true }
    value: { type: object, notnull: true }
   relations:
    lesson: {onDelete: CASCADE, local: lesson_id, foreign: id}
    fields: {onDelete: CASCADE, local: field_id, foreign: id}
# Fields Config
student_form_fields:
  actAs: 
    Timestampable: ~
  columns:
   field_id: { type: integer, notnull: true }  
  relations:
   fields: {onDelete: CASCADE, local: field_id, foreign: id}

teacher_form_fields:
  actAs: 
    Timestampable: ~
  columns:
   field_id: { type: integer, notnull: true }  
  relations:
   fields: {onDelete: CASCADE, local: field_id, foreign: id}

lesson_form_fields:
  actAs: 
    Timestampable: ~
  columns:
   field_id: { type: integer, notnull: true }  
  relations:
   fields: {onDelete: CASCADE, local: field_id, foreign: id}